spring.application.name=expense-tracker
server.port=8081
# Root logging level
logging.level.root=INFO

# Enable DEBUG logs for this application
logging.level.com.diligent.expensetracker=DEBUG

# Reduce Spring framework log noise
logging.level.org.springframework=WARN